state = (0 << 0)
detach = 0
detachedby = -1
follow_golf = 0
targetgolf = -4
camzoom = 1
max_zoom = 100
targetzoom = 1
zoomspd = 0.01
lastcollect = -1
ranksprite = spr_ranks_hud
hudfillsprite = spr_ranks_hudfill
previoushudsprite = ranksprite
color_array = array_create(1, 0)
collect_shake = 0
combobubblevisible = 1
lock = 0
comboend = 0
followtarget = -4
followspeed = 10
previousrank = 0
rank_scale = 1
cam_x = 0
cam_y = 0
camdirectx = 0
camdirecty = 0
counter = 0
rotates = 0
idkanymore = cos(rotates)
tracktilt = 0
original_cam_width = obj_screensizer.actual_width
original_cam_height = obj_screensizer.actual_height
coop_zoom_width = ((original_cam_width / 4) * 1.5)
coop_zoom_height = ((original_cam_height / 4) * 1.5)
player = (obj_player1.spotlight == 1 ? obj_player1 : obj_player2)
target = player
cam_width = camera_get_view_width(view_camera[0])
cam_height = camera_get_view_height(view_camera[0])
tx = target.x
ty = target.y
hud_posY = 0
fontpalettespr = spr_font_palette
if (obj_player.character == "N" || (obj_player.character == "P" && obj_player.ispeppino == 0))
{
    fontpalettespr = spr_palette_font_noise
    pizzascore_sprite = spr_pizzascore_noise
    pizzascore_topping1 = 4206
    pizzascore_topping2 = 4207
    pizzascore_topping3 = 4205
    pizzascore_topping4 = 4208
}
else
{
    fontpalettespr = spr_font_palette
    pizzascore_sprite = spr_pizzascore
    pizzascore_topping1 = 3836
    pizzascore_topping2 = 581
    pizzascore_topping3 = 1318
    pizzascore_topping4 = 1063
}
pizzascore_index = 0
pizzascore_number = sprite_get_number(pizzascore_sprite)
n = 0
image_speed = 0.05
alarm[1] = -1
global.seconds = 59
global.minutes = 0
global.miniboss = 0
angle = 0
frame = 0
global.pizza = 0
global.pizzameter = 0
global.pillarhunger = 4000
basement = 0
shake_mag = 0
shake_mag_acc = 0
zoom = 0
chargecamera = 0
alpha = 1
zoomh = obj_screensizer.actual_height
zoomw = obj_screensizer.actual_width
global.maxwave = 0
global.wave = 0
ded = 0
player = 530
spr_player = -4
spr_speedbarHUD = -4
spr_speedbar_index = bg_chateauscrolldeco
shoving = 0
bang = 0
image_speed = 0.35
p2pdistance = 0
p2pdistancex = 0
bound_camera = 0
global.timedgate = 0
healthshake = 0
healthold = 8
healthshaketime = 0
playerhealthup = 0
hud_xx = (121 + irandom_range((-collect_shake), collect_shake))
hud_yy = ((90 + irandom_range((-collect_shake), collect_shake)) + hud_posY)
smoothcam = 0
