global.style = 0
global.stylethreshold = 0
global.stylemultiplier = 0
alpha = 1
index = 0
sprite = spr_mild
global.baddiespeed = 1
global.baddiepowerup = 0
global.baddierage = 0
bubble_x = (obj_screensizer.actual_width - 280)
bubble_y = 90
active = 1
