hsp = 0
vsp = 0
depth = -70
movespeed = 2
image_alpha = 0.75
start_alpha = image_alpha
image_speed = 0.35
blur_effect = 0
paletteselect = 0
spr_palette = palette_pepgoblin
state = (0 << 0)
fadein = 0
usepalette = 0
snd = fmod_event_create_instance("event:/sfx/enemies/johnghost")
