depth = 1
global.afterimage_list = ds_list_create()
alpha = array_create((8 << 0), 1)
alpha[(2 << 0)] = 0.5
shd_alpha = shader_get_uniform(shd_firemouth_afterimage, "newAlpha")
shd_color_red = shader_get_uniform(shd_color_afterimage, "red")
shd_color_green = shader_get_uniform(shd_color_afterimage, "green")
shd_color_blue = shader_get_uniform(shd_color_afterimage, "blue")
aftimg_shader = 16
global.mach_color1 = make_colour_rgb(255, 0, 0)
global.mach_color2 = make_colour_rgb(36, 228, 102)
global.mach_color3 = make_colour_rgb(178, 26, 231)
global.mach_color4 = global.mach_color1
global.mach_color5 = global.mach_color2
global.mach_color6 = global.mach_color3
global.mach_outlinecolor = 0
global.custom_mach_colors = 0
global.custom_mach_color1 = global.mach_color1
global.custom_mach_color2 = global.mach_color2
global.custom_mach_color3 = global.mach_color3
global.custom_mach_color4 = global.mach_color4
global.custom_mach_color5 = global.mach_color5
global.custom_mach_color6 = global.mach_color6
global.custom_mach_outline = global.mach_outlinecolor
global.mach_color_number = 6
color1 = [global.mach_color1, global.mach_color2, global.mach_color3, global.mach_color4, global.mach_color5, global.mach_color6]
color2 = global.mach_outlinecolor
colortimer = 0
