levelarray = array_create(0)
show = 0
text_xscale = ((obj_screensizer.actual_width - 64) / sprite_get_width(spr_tutorialbubble))
text_yscale = 2
text_y = (-((sprite_get_height(spr_tutorialbubble) * text_yscale)))
text_sprite_height = sprite_get_height(spr_tutorialbubble)
text_xpad = 0
text_state = (18 << 0)
text_ystart = 16
text_vsp = 0
text_wave_x = 0
text_wave_y = 0
tex_x = 0
surfclip = -4
surffinal = -4
depth = 0
wave_timer = 0
