scr_initenemy()
scr_pizzaface_p2_init_sounds()
leveldown = 0
fishcount = 1
throwsword = 0
lastattack = -1
miniguncount = 0
brickcount = 0
brick = 0
idle_buffer = 0
availablemoves = []
movecount[(0 << 0)] = 0
movecount[(1 << 0)] = 0
movecount[(2 << 0)] = 0
movecount[(3 << 0)] = 0
movecount[(4 << 0)] = 0
bullethit = 0
parryable = 0
instantkillable = 0
flameID = -4
playerhit = 0
introbuffer = 80
important = 1
stompable = 0
shakestun = 0
elite = 1
elitehit = 8
prevhp = elitehit
turned = 0
wastedhits = 0
state = (134 << 0)
hitboxID = -4
attackspeed = 0
hitboxID = -4
destroyable = 1
idle_max = 240
idle_timer = idle_max
grav = 0.5
hsp = 0
vsp = 0
stunned = 0
alarm[0] = 150
roaming = 1
collectdrop = 5
flying = 0
straightthrow = 0
cigar = 0
cigarcreate = 0
stomped = 0
shot = 0
reset = 0
flash = 0
landspr = spr_pizzahead_giddy
idlespr = spr_pizzahead_giddy
fallspr = spr_pizzahead_giddy
stunfallspr = spr_pizzahead_stun
walkspr = spr_pizzahead_giddy
turnspr = spr_pizzahead_giddy
recoveryspr = spr_pizzahead_giddy
grabbedspr = spr_pizzahead_stun
scaredspr = spr_pizzahead_giddy
ragespr = spr_pizzahead_giddy
hp = 1
slapped = 0
grounded = 1
birdcreated = 0
boundbox = 0
spr_dead = spr_pizzahead_stun
important = 0
heavy = 1
paletteselect = 0
spr_palette = palette_cheeseslime
grabbedby = 0
stuntouchbuffer = 0
scaredbuffer = 0
cooldown = 40
phase = 1
dir = 1
woosh = 0
flickertime = 0
touchedground = 0
cowcrate = 0
alarm[8] = 1200
