function scr_initinput(argument0) //scr_initinput
{
    if (argument0 == undefined)
        argument0 = 1
    if argument0
        ini_open("saveData.ini")
    global.key_up = ini_read_string("ControlsKeys", "up", 38)
    global.key_right = ini_read_string("ControlsKeys", "right", 39)
    global.key_left = ini_read_string("ControlsKeys", "left", 37)
    global.key_down = ini_read_string("ControlsKeys", "down", 40)
    global.key_jump = ini_read_string("ControlsKeys", "jump", 90)
    global.key_slap = ini_read_string("ControlsKeys", "slap", 88)
    global.key_taunt = ini_read_string("ControlsKeys", "taunt", 67)
    global.key_shoot = ini_read_string("ControlsKeys", "shoot", 65)
    global.key_attack = ini_read_string("ControlsKeys", "attack", 16)
    global.key_start = ini_read_string("ControlsKeys", "start", 27)
    global.key_chainsaw = ini_read_string("ControlsKeys", "chainsaw", 86)
    global.key_upC = ini_read_string("ControllerButton", "up", 32781)
    global.key_rightC = ini_read_string("ControllerButton", "right", 32784)
    global.key_leftC = ini_read_string("ControllerButton", "left", 32783)
    global.key_downC = ini_read_string("ControllerButton", "down", 32782)
    global.key_jumpC = ini_read_string("ControllerButton", "jump", 32769)
    global.key_slapC = ini_read_string("ControllerButton", "slap", 32771)
    global.key_tauntC = ini_read_string("ControllerButton", "taunt", 32772)
    global.key_shootC = ini_read_string("ControllerButton", "shoot", 32770)
    global.key_attackC = ini_read_string("ControllerButton", "attack", 32776)
    global.key_startC = ini_read_string("ControllerButton", "start", 32778)
    global.key_chainsawC = ini_read_string("ControllerButton", "chainsaw", 32773)
    global.key_superjumpC = ini_read_string("ControllerButton", "superjump", -4)
    global.key_groundpoundC = ini_read_string("ControllerButton", "groundpound", -4)
    global.gamepad_deadzone = ini_read_real("ControllerConfig", "deadzone", 0.4)
    global.gamepad_deadzone_vertical = ini_read_real("ControllerConfig", "deadzone_vert", 0.65)
    global.gamepad_deadzone_horizontal = ini_read_real("ControllerConfig", "deadzone_horiz", 0.5)
    global.gamepad_deadzone_press = ini_read_real("ControllerConfig", "deadzonepress", 0.5)
    global.gamepad_deadzone_superjump = ini_read_real("ControllerConfig", "deadzonesuperjump", 0.56)
    global.gamepad_deadzone_crouch = ini_read_real("ControllerConfig", "deadzonecrouch", 0.46)
    global.gamepad_superjump = ini_read_real("ControllerConfig", "superjump", 1)
    global.gamepad_groundpound = ini_read_real("ControllerConfig", "groundpound", 1)
    if argument0
        ini_close()
}

