notification_push((19 << 0), [room])
image_speed = 0.5
hsp = 0
vsp = 0
grav = 0.5
xoffset = 0
movespeed = 0
grounded = 0
bounce = 1
blur_effect = 2
vsp_carry = 0
hsp_carry = 0
platformid = -4
paletteselect = 0
spr_palette = bg_chateauscrolldeco
alarm[0] = 200
alarm[1] = 5
kicked = 0
depth = (obj_player1.depth + 1)
up = 0
hitbox = 0
dashcloudtimer = 0
speedline = 0
