if (instance_number(object_index) > 1)
{
    instance_destroy()
    return;
}
global.throwarc = 1
global.hidetiles = 0
global.cowboyhat = 0
global.leveltosave = -4
global.leveltorestart = -4
global.hub_bgsprite = -4
global.offload_tex = -4
global.bossplayerhurt = 0
global.boss_invincible = 0
global.highest_combo = 0
global.player_damage = 0
global.vomitamt = 0
global.tribecheesecensor = 1
global.mrpinchcensor = 1
global.peppino_damage = 0
global.gustavo_damage = 0
global.enemykilled = 0
global.johnresurrection = 0
global.startgate = 0
global.heatmeter = 0
global.bossintro = 0
global.palettetexture = -4
global.palettesurface = -4
global.palettesurfaceclip = -4
global.levelattempts = 0
global.exitrank = 0
global.playerhit = 0
global.door_sprite = spr_door
global.door_index = 0
global.pistol = 0
global.shootkeyattack = 0
global.choosetoppingspos = 284600
global.blueeffects = 0
global.smoothcamera = 0
global.tvbackground = 1
global.level_realseconds = 0
global.level_realminutes = 0
global.optionsbackroom = 756
global.panicshadetimer = 0
pogo_afterimage = 0
pogosplode = 0
uppercutbuffer = 0
cangrab = 0
chainsaweffect = -4
purpleshine = 0
purpleguy = 0
shirtspr = spr_palettedresserdebris_pep
dynamitebuff = 0
dynamiteindex = 0
dynamitereal = 0
dynamiteholdtimer = 0
dynamitehold = 0
dynamitesjump = 0
dynamitebuffer = 0
throwforce = 0
webspeed = 0
trickjumpsprite = spr_plug
trickjumpindex = 0
trickjumpvsp = 0
trickjumpmovespeed = 0
trickjumphsp = 0
machreset = 0
realdoublejump = 0
firemouthballbuffer = 0
golfdashbuffer = 0
homingattackfall = 0
slopedirection = 0
homingattack = 0
dropdash = 0
spindashcharge = 0
gusuppercutbuff = 0
ratmissilenotif = 0
ratdashnotif = 0
ratmissilecool = 0
ratmissilecharge = 0
chainsawrev = 0
ramp_buffer = 0
glidemode = 0
payoutramp = 0
hasjumped = 0
groundpoundjumpanim = 0
uncrouch = 0
parryID = -4
bodyslam_notif = 0
swingdingthrow = 0
sjumptimer = 0
can_jump = 0
coyote_time = 0
invtime = 0
parry_lethal = 0
usepalette = 1
jetpackeffect = 0
superchargebuffer = 0
fireasseffect = 0
pistolanim = -4
pistolindex = 0
pistolcooldown = 0
pistolchargesound = 0
policetaxi = 0
collision_flags = 0
breakdance_pressed = 0
restartbuffer = 0
jetpackdash = 0
flamecloud_buffer = 0
rankpos_x = x
rankpos_y = y
transformationlives = 0
punch_afterimage = 0
superchargecombo_buffer = -1
superattackstate = (0 << 0)
afterimagedebris_buffer = 0
scale_xs = 1
scale_ys = 1
verticalbuffer = 0
verticalstate = (0 << 0)
webID = -4
float = 0
boxxedpepjump = 10
boxxedpepjumpmax = 10
icemovespeed = 0
prevmove = 0
prevhsp = 0
prevstate = (0 << 0)
prevxscale = 1
prevsprite = sprite_index
move = 0
prevmovespeed = 0
previcemovespeed = 0
icedir = 1
icemomentum = 0
savedicedir = 1
ispeppino = 1
isgustavo = 0
jumped = 1
grav = 0.5
hsp = 0
vsp = 0
vsp_carry = 0
hsp_carry = 0
rocketvsp = 0
sticking = 0
platformid = -4
xscale = 1
yscale = 1
facehurt = 0
steppy = 0
steppybuffer = 0
depth = -7
movespeed = 19
jumpstop = 0
ramp = 0
ramp_points = 0
bombup_dir = 1
knightmomentum = 0
downknight = 0
grabbingenemy = 0
blur_effect = 0
firemouth_dir = 1
firemouth_max = 10
firemouth_buffer = firemouth_max
firemouth_afterimage = 0
cow_buffer = 0
balloonbuffer = 0
shoot_buffer = 0
shoot_max = 20
dynamite_inst = -4
golfid = -4
bombgrabID = -4
barrelslope = 0
barrel_maxmovespeed = 16
barrel_maxfootspeed = 10
barrel_rollspeed_threshold = 10
barrel_accel = 1
barrel_deccel = 1
barrel_slopeaccel = 0.25
barrel_slopedeccel = 0.5
barrelroll_slopeaccel = 0.5
barrelroll_slopedeccel = 0.35
hurt_buffer = -1
hurt_max = 120
invhurt_buffer = 0
invhurt_max = 30
ratmount_movespeed = 8
ratmount_fallingspeed = 0
ratgrabbedID = -4
ratpowerup = -4
ratshootbuffer = 0
rateaten = 0
gustavodash = 0
brick = 0
ratmountpunchtimer = 25
gustavokicktimer = 5
cheesepep_buffer = 0
cheesepep_max = 10
pepperman_accel = 0.25
pepperman_deccel = 0.5
pepperman_accel_air = 0.15
pepperman_deccel_air = 0.25
pepperman_maxhsp_normal = 6
pepperman_jumpspeed = 11
pepperman_grabID = -4
shoulderbash_mspeed_start = 10
shoulderbash_mspeed_loop = 8
shoulderbash_jumpspeed = 10
visible = true
state = (18 << 0)
jumpAnim = 1
landAnim = 0
machslideAnim = 0
moveAnim = 1
stopAnim = 1
crouchslideAnim = 1
crouchAnim = 1
machhitAnim = 0
stompAnim = 0
inv_frames = 0
hurted = 0
autodash = 0
mach2 = 0
stop_buffer = 8
slope_buffer = 8
stop_max = 16
parry = 0
parry_inst = -4
taunt_to_parry_max = 8
parrytimer = 0
parry_count = 0
parry_max = 8
is_firing = 0
input_buffer_jump = 0
input_buffer_jump_negative = 0
input_buffer_shoot = 0
input_buffer_secondjump = 8
input_buffer_highjump = 8
input_buffer_walljump = 0
input_buffer_slap = 0
input_attack_buffer = 0
input_finisher_buffer = 0
input_up_buffer = 0
input_down_buffer = 0
hit_connected = 0
player_x = x
player_y = y
targetRoom = Loadiingroom
targetDoor = "A"
scr_init_input()
flash = 0
key_particles = 0
barrel = 0
bounce = 0
a = 0
idle = 0
attacking = 0
slamming = 0
superslam = 0
grounded = 1
grinding = 0
machpunchAnim = 0
punch = 0
machfreefall = 0
shoot = 0
instakillmove = 0
stunmove = 0
windingAnim = 0
facestompAnim = 0
ladderbuffer = 0
toomuchalarm1 = 0
toomuchalarm2 = 0
idleanim = 0
momemtum = 0
cutscene = 0
grabbing = 0
dir = xscale
shotgunAnim = 0
goingdownslope = 0
goingupslope = 0
fallinganimation = 0
bombpeptimer = 100
suplexmove = 0
suplexhavetomash = 0
anger = 0
angry = 0
baddiegrabbedID = 0
spr_palette = spr_peppalette
character = "P"
scr_characterspr()
paletteselect = 1
colorchange = 0
treasure_x = 0
treasure_y = 0
treasure_room = 0
wallspeed = 0
tauntstoredstate = (0 << 0)
tauntstoredmovespeed = 6
tauntstoredsprite = spr_player_idle
taunttimer = 20
tauntstoredvsp = 0
tauntstoredisgustavo = 0
tube_id = -1
backtohubstartx = x
backtohubstarty = y
backtohubroom = 0
slapcharge = 0
slaphand = 1
slapbuffer = 8
slapflash = 0
freefallsmash = 0
costumercutscenetimer = 0
heavy = 0
lastroom_x = 0
lastroom_y = 0
lastroom = 0
lastTargetoor = "A"
hallway = 0
savedhallway = 0
hallwaydirection = 0
savedhallwaydirection = 0
vhallwaydirection = 0
savedvhallwaydirection = 0
verticalhallway = 0
savedverticalhallway = 0
vertical_x = x
verticalhall_vsp = 0
box = 0
roomstartx = 0
roomstarty = 0
swingdingbuffer = 0
swingdingdash = 0
lastmove = 0
backupweapon = 0
stickpressed = 0
spotlight = 1
macheffect = 0
chargeeffectid = 741
dashcloudid = 741
crazyruneffectid = 741
fightball = 0
superslameffectid = 741
speedlineseffectid = 741
angryeffectid = 741
thrown = 0
transformationsnd = 0
mach1snd = -1
mach2snd = -1
mach3snd = -1
machsnd = fmod_event_create_instance("event:/sfx/pep/mach")
fmod_event_instance_set_parameter(machsnd, "state", 0, 1)
jumpsnd = fmod_event_create_instance("event:/sfx/pep/jump")
machrollsnd = fmod_event_create_instance("event:/sfx/pep/machroll")
weeniebumpsnd = fmod_event_create_instance("event:/sfx/weenie/bump")
knightslidesnd = fmod_event_create_instance("event:/sfx/knight/slide")
gravecorpsesnd = fmod_event_create_instance("event:/sfx/pep/gravecorpse")
barrelslidesnd = fmod_event_create_instance("event:/sfx/barrel/slide")
barrelbumpsnd = fmod_event_create_instance("event:/sfx/barrel/bump")
waterslidesnd = fmod_event_create_instance("event:/sfx/misc/waterslide")
mrpinchsnd = fmod_event_create_instance("event:/sfx/misc/mrpinch")
hamkuffsnd = fmod_event_create_instance("event:/sfx/misc/hamkuff")
ratmountmachsnd = fmod_event_create_instance("event:/sfx/ratmount/mach")
ratmountballsnd = fmod_event_create_instance("event:/sfx/ratmount/ball")
ratmountgroundpoundsnd = fmod_event_create_instance("event:/sfx/ratmount/groundpound")
ratmountpunchsnd = fmod_event_create_instance("event:/sfx/ratmount/punch")
cheeseballsnd = fmod_event_create_instance("event:/sfx/cheese/ball")
boxxedspinsnd = fmod_event_create_instance("event:/sfx/boxxed/spin")
pizzapeppersnd = fmod_event_create_instance("event:/sfx/pep/pizzapepper")
ratdeflatesnd = fmod_event_create_instance("event:/sfx/rat/deflate")
ghostspeedsnd = fmod_event_create_instance("event:/sfx/pep/ghostspeed")
freefallsnd = fmod_event_create_instance("event:/sfx/pep/freefall")
rollgetupsnd = fmod_event_create_instance("event:/sfx/pep/rollgetup")
knightslide = -1
bombpep1snd = -1
mach4snd = -1
tumble2snd = -1
tumble1snd = -1
tumble3snd = -1
tumblesnd = fmod_event_create_instance("event:/sfx/pep/tumble")
snd_uppercut = fmod_event_create_instance("event:/sfx/pep/uppercut")
snd_dive = fmod_event_create_instance("event:/sfx/pep/dive")
snd_crouchslide = fmod_event_create_instance("event:/sfx/pep/crouchslide")
tumbleintro = 0
rocketsnd = -1
hamkuffID = -4
snd_voiceok = fmod_event_create_instance("event:/sfx/voice/ok")
snd_voicetransfo = fmod_event_create_instance("event:/sfx/voice/transfo")
snd_voiceouttransfo = fmod_event_create_instance("event:/sfx/voice/outtransfo")
snd_voicehurt = fmod_event_create_instance("event:/sfx/voice/hurt")
snd_dashpad = fmod_event_create_instance("event:/sfx/misc/dashpad")
animatronicsnd = fmod_event_create_instance("event:/sfx/pep/animatronic")
burpsnd = fmod_event_create_instance("event:/sfx/enemies/burp")
mortslap = fmod_event_create_instance("event:/sfx/mort/mortslap")
global.snd_escaperumble = fmod_event_create_instance("event:/sfx/misc/escaperumble")
global.snd_johndead = fmod_event_create_instance("event:/sfx/enemies/johndead")
global.snd_spaceship = fmod_event_create_instance("event:/sfx/misc/spaceship")
global.snd_fakesanta = fmod_event_create_instance("event:/sfx/enemies/fakesanta")
global.snd_rankup = fmod_event_create_instance("event:/sfx/ui/rankup")
global.snd_fireass = fmod_event_create_instance("event:/sfx/pep/fireass")
global.snd_pizzafacemoving = fmod_event_create_instance("event:/sfx/pizzaface/moving")
global.snd_rankdown = fmod_event_create_instance("event:/sfx/ui/rankdown")
global.snd_rank = fmod_event_create_instance("event:/music/rank")
global.snd_parry = fmod_event_create_instance("event:/sfx/pep/parry")
global.snd_breakblock = fmod_event_create_instance("event:/sfx/misc/breakblock")
global.snd_collect = fmod_event_create_instance("event:/sfx/misc/collect")
global.snd_bellcollect = fmod_event_create_instance("event:/sfx/misc/bellcollect")
global.snd_cardflip = fmod_event_create_instance("event:/sfx/misc/cardflip")
global.snd_explosion = fmod_event_create_instance("event:/sfx/misc/explosion")
global.snd_cheesejump = fmod_event_create_instance("event:/sfx/pep/cheesejump")
global.snd_ventilator = fmod_event_create_instance("event:/sfx/misc/ventilator")
global.snd_trashjump1 = fmod_event_create_instance("event:/sfx/misc/trashjump1")
global.snd_thunder = fmod_event_create_instance("event:/sfx/knight/thunder")
global.snd_captaingoblinshoot = fmod_event_create_instance("event:/sfx/misc/captaingoblinshoot")
global.snd_golfjingle = fmod_event_create_instance("event:/sfx/misc/golfjingle")
global.snd_mrstickhat = fmod_event_create_instance("event:/sfx/misc/mrstickhat")
global.snd_alarm = fmod_event_create_instance("event:/sfx/enemies/alarm")
global.snd_slidersfx = fmod_event_create_instance("event:/sfx/ui/slidersfx")
global.snd_slidermusic = fmod_event_create_instance("event:/sfx/ui/slidermusic")
global.snd_slidermaster = fmod_event_create_instance("event:/sfx/ui/slidersfxmaster")
global.snd_bossbeaten = fmod_event_create_instance("event:/sfx/misc/bossbeaten")
superjumpholdsnd = -1
superjumpprepsnd = -1
superjumpsnd = fmod_event_create_instance("event:/sfx/pep/superjump")
suplexdashsnd = fmod_event_create_instance("event:/sfx/pep/suplexdash")
pogospeed = 2
pogocharge = 100
pogochargeactive = 0
wallclingcooldown = 10
bombcharge = 0
flashflicker = 0
flashflickertime = 0
kickbomb = 0
doublejump = 0
pogospeedprev = 0
fightballadvantage = 0
coopdelay = 0
supercharged = 0
superchargedeffectid = 741
used_supercharge = 0
pizzashield = 0
pizzashieldid = 741
pizzapepper = 0
transformation[0] = (51 << 0)
transformation[1] = (47 << 0)
transformation[2] = (38 << 0)
transformation[3] = (33 << 0)
transformation[4] = (21 << 0)
transformation[5] = (24 << 0)
transformation[6] = (25 << 0)
transformation[7] = (30 << 0)
transformation[8] = (29 << 0)
transformation[9] = (10 << 0)
transformation[10] = (9 << 0)
transformation[11] = (59 << 0)
transformation[12] = (31 << 0)
transformation[13] = (89 << 0)
transformation[14] = (112 << 0)
transformation[15] = (16 << 0)
transformation[16] = (17 << 0)
transformation[17] = (11 << 0)
transformation[18] = (150 << 0)
transformation[19] = (146 << 0)
transformation[20] = (184 << 0)
transformation[21] = (186 << 0)
transformation[22] = (52 << 0)
transformation[23] = (53 << 0)
transformation[24] = (54 << 0)
transformation[25] = (116 << 0)
transformation[26] = (114 << 0)
transformation[27] = (113 << 0)
transformation[28] = (22 << 0)
transformation[29] = (32 << 0)
transformation[30] = (49 << 0)
transformation[31] = (48 << 0)
transformation[32] = (13 << 0)
transformation[33] = (14 << 0)
transformation[34] = (12 << 0)
transformation[35] = (35 << 0)
transformation[36] = (34 << 0)
transformation[37] = (185 << 0)
transformation[38] = (26 << 0)
transformation[39] = (31 << 0)
transformation[40] = (115 << 0)
keysound = 0
c = 0
stallblock = 0
breakdance = 50
skateboarding = 0
hitX = x
hitY = y
hithsp = 0
hitvsp = 0
hitstunned = 0
hitxscale = 1
stunned = 0
hitLag = 25
supercharge = 0
mort = 0
sjumpvsp = -12
freefallvsp = 15
hitlist = ds_list_create()
animlist = ds_list_create()
lungeattackID = -4
lunge_hits = 0
lunge_hit_buffer = 0
lunge_buffer = 0
finisher = 0
finisher_buffer = 0
finisher_hits = 0
uplaunch = 0
downlaunch = 0
dash_doubletap = 0
finishingblow = 0
launch = 0
launched = 1
launch_buffer = 0
jetpackfuel = 0
jetpackmax = 200
walljumpbuffer = 0
farmerpos = 0
clowntimer = 0
knightmiddairstop = 0
knightmove = -1
if (!variable_global_exists("saveroom"))
{
    global.combodropped = 0
    global.saveroom = ds_list_create()
    global.escaperoom = ds_list_create()
    global.lap = 0
    global.laps = 0
    global.playerhealth = 8
    global.playerhealth_threshold = 0
    global.instancelist = ds_list_create()
    global.followerlist = ds_list_create()
    global.maxrailspeed = 2
    global.railspeed = global.maxrailspeed
    global.levelreset = 0
    global.temperature = 0
    global.temperature_spd = 0.01
    global.temp_thresholdnumber = 5
    global.use_temperature = 0
    global.timedgatetimer = 0
    global.timedgatetime = 0
    global.timedgateid = -4
    global.timedgatetimemax = 0
    global.key_inv = 0
    global.shroomfollow = 0
    global.cheesefollow = 0
    global.tomatofollow = 0
    global.sausagefollow = 0
    global.pineapplefollow = 0
    global.pepanimatronic = 0
    global.keyget = 0
    global.collect = 0
    global.collectN = 0
    global.hats = 0
    global.extrahats = 0
    global.treasure = 0
    global.combo = 0
    global.previouscombo = 0
    global.combotime = 0
    global.combotimepause = 0
    global.prank_enemykilled = 0
    global.prank_cankillenemy = 1
    global.tauntcount = 0
    global.comboscore = 0
    global.savedcomboscore = 0
    global.savedcombo = 0
    global.heattime = 0
    global.pizzacoin = 0
    global.toppintotal = 1
    global.hit = 0
    global.baddieroom = ds_list_create()
    global.hp = 2
    global.gotshotgun = 0
    global.showgnomelist = 1
    global.panic = 0
    global.snickchallenge = 0
    global.golfhit = 0
    global.style = -1
    global.secretfound = 0
    global.shotgunammo = 0
    global.monsterspeed = 0
    global.monsterlives = 3
    global.giantkey = 0
    global.coop = 0
    global.baddiespeed = 1
    global.baddiepowerup = 0
    global.baddierage = 0
    global.style = 0
    global.stylethreshold = 0
    global.pizzadelivery = 0
    global.failcutscene = 0
    global.pizzasdelivered = 0
    global.spaceblockswitch = 1
    global.gerome = 0
    global.pigtotal_add = 0
    global.bullet = 0
    global.fuel = 5
    global.bigfont = font_add_sprite_ext(spr_font, "ABCDEFGHIJKLMNOPQRSTUVWXYZ!.1234567890:", 1, 0)
    global.smallfont = font_add_sprite_ext(spr_smallerfont, "ABCDEFGHIJKLMNOPQRSTUVWXYZ!.:?1234567890", 1, 0)
    global.tutorialfont = font_add_sprite_ext(spr_tutorialfont, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!,.:0123456789'?-", 1, 2)
    global.creditsfont = font_add_sprite_ext(spr_creditsfont, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz.:!0123456789?'\"ÁÉÍÓÚáéíóú_-[]▼()&#风雨廊桥전태양*яиБжидГзвбнль", 1, 2)
    global.moneyfont = font_add_sprite_ext(spr_stickmoney_font, "0123456789$-", 1, 0)
    global.font_map = ds_map_create()
    ds_map_set(global.font_map, "bigfont_en", global.bigfont)
    ds_map_set(global.font_map, "smallfont_en", global.smallfont)
    ds_map_set(global.font_map, "tutorialfont_en", global.tutorialfont)
    ds_map_set(global.font_map, "creditsfont_en", global.creditsfont)
    var key = ds_map_find_first(global.lang_map)
    for (var i = 0; i < ds_map_size(global.lang_map); i++)
    {
        var lang = ds_map_find_value(global.lang_map, key)
        if ds_map_find_value(lang, "custom_fonts")
        {
            ds_map_set(global.font_map, concat("tutorialfont_", key), lang_get_custom_font("tutorialfont", lang))
            ds_map_set(global.font_map, concat("creditsfont_", key), lang_get_custom_font("creditsfont", lang))
            ds_map_set(global.font_map, concat("bigfont_", key), lang_get_custom_font("bigfont", lang))
            ds_map_set(global.font_map, concat("smallfont_", key), lang_get_custom_font("smallfont", lang))
        }
        key = ds_map_find_next(global.lang_map, key)
    }
    global.collectfont = font_add_sprite_ext(spr_font_collect, "0123456789", 1, 0)
    global.combofont = font_add_sprite_ext(spr_font_combo, "0123456789/:", 1, 0)
    global.combofont2 = font_add_sprite_ext(spr_tv_combobubbletext, "0123456789", 1, 0)
    global.wartimerfont1 = font_add_sprite_ext(spr_wartimer_font1, "1234567890", 1, 0)
    global.wartimerfont2 = font_add_sprite_ext(spr_wartimer_font2, "1234567890", 1, 0)
    global.ammorefill = 0
    global.ammoalt = 1
    global.mort = 0
    global.stylelock = 0
    global.attackstyle = 0
    global.pummeltest = 1
    global.horse = 0
    global.checkpoint_room = -4
    global.checkpoint_door = "A"
    global.kungfu = 0
    global.graffiticount = 0
    global.graffitimax = 20
    global.noisejetpack = 0
    global.hasfarmer = array_create(3, 0)
    global.savedattackstyle = -4
    global.throw_frame = 0
    global.throw_frame[659] = 11
    global.throw_frame[661] = 13
    global.throw_frame[660] = 18
    global.throw_frame[655] = 6
    global.throw_frame[676] = 2
    global.throw_frame[333] = 7
    global.throw_frame[38] = 2
    global.throw_frame[678] = 2
    global.throw_frame[657] = 2
    global.throw_frame[658] = 8
    global.throw_frame[114] = 8
    global.throw_frame[665] = 6
    global.throw_frame[670] = 3
    global.throw_frame[1020] = 8
    global.throw_frame[668] = 15
    global.throw_frame[667] = 10
    global.throw_frame[666] = 2
    global.throw_frame[373] = 6
    global.throw_frame[647] = 9
    global.throw_frame[648] = 9
    global.throw_frame[623] = 9
    global.throw_frame[377] = 13
    global.throw_frame[686] = 3
    global.throw_frame[1053] = 7
    global.throw_frame[476] = 11
    global.throw_frame[32] = 13
    global.throw_frame[303] = 13
    global.throw_sprite = bg_chateauscrolldeco
    global.throw_sprite[659] = 144
    global.throw_sprite[661] = 175
    global.throw_sprite[660] = 526
    global.throw_sprite[655] = 289
    global.throw_sprite[676] = 501
    global.throw_sprite[333] = 550
    global.throw_sprite[38] = 320
    global.throw_sprite[678] = 372
    global.throw_sprite[657] = 290
    global.throw_sprite[658] = 404
    global.throw_sprite[114] = 404
    global.throw_sprite[665] = 430
    global.throw_sprite[670] = 300
    global.throw_sprite[1020] = 1641
    global.throw_sprite[668] = 449
    global.throw_sprite[667] = 366
    global.throw_sprite[666] = 516
    global.throw_sprite[373] = 550
    global.throw_sprite[647] = 595
    global.throw_sprite[648] = 595
    global.throw_sprite[623] = 595
    global.throw_sprite[377] = 2330
    global.throw_sprite[686] = 3971
    global.throw_sprite[1053] = 28
    global.throw_sprite[476] = 3271
    global.throw_sprite[32] = 3112
    global.throw_sprite[303] = 876
    global.reset_timer = 0
    global.reset_timer[659] = 200
    global.reset_timer[661] = 200
    global.reset_timer[660] = 200
    global.reset_timer[655] = 200
    global.reset_timer[676] = 100
    global.reset_timer[333] = 400
    global.reset_timer[38] = 100
    global.reset_timer[678] = 100
    global.reset_timer[657] = 150
    global.reset_timer[658] = 200
    global.reset_timer[114] = 200
    global.reset_timer[665] = 100
    global.reset_timer[670] = 200
    global.reset_timer[1020] = 200
    global.reset_timer[668] = 200
    global.reset_timer[667] = 100
    global.reset_timer[666] = 200
    global.reset_timer[373] = 100
    global.reset_timer[647] = 60
    global.reset_timer[648] = 60
    global.reset_timer[623] = 60
    global.reset_timer[377] = 10
    global.reset_timer[686] = 100
    global.reset_timer[1053] = 100
    global.reset_timer[476] = 100
    global.reset_timer[32] = 100
    global.reset_timer[303] = 100
}
angle = 0
mach4mode = 0
railmomentum = 0
railmovespeed = 0
raildir = 1
boxxed = 0
boxxeddash = 0
boxxeddashbuffer = 0
cheesepeptimer = -1
cheeseballbounce = 0
slopejump = 0
slopejumpx = 0
hooked = 0
swingdingendcooldown = 0
crouchslipbuffer = 0
breakdance_speed = 0.25
notecreate = 50
jetpackbounce = 0
firemouthflames = 0
ghostdash = 0
ghostpepper = 0
ghosteffect = 0
ghostbump = 1
ghostbumpbuffer = -1
dashcloudtimer = 0
grabclimbbuffer = 0
gustavohitwall = 0
gusdashpadbuffer = 0
holycross = 0
knightdowncloud = 0
piledrivereffect = 0
fireasslock = 0
pistolcharge = 0
pistolcharged = 0
pistolchargebuffer = 0
pistolchargedelay = 5
pistolchargeshooting = 0
pistolchargeshot = 8
pistolchargeeffect = 0
gravesurfingjumpbuffer = 0
spinsndbuffer = 5
boxxedspinbuffer = 0
noisebossscream = 0
gallopingsnd = fmod_event_create_instance("event:/sfx/misc/galloping")
