wave_x = 0
crosshair_x = x
crosshair_y = y
wave_xlimit = 156
turn = 1
shoot_max = 125
saved_xs = ((!global.panic) ? 1 : -1)
state = (0 << 0)
image_speed = 0.35
depth = -8
captain_x = 160
captain_y = (obj_screensizer.actual_height + sprite_get_height(spr_captaingoblin_canon))
canon_y = (obj_screensizer.actual_height + sprite_get_height(spr_captaingoblin_canon))
captain_xto = 234
captain_index = 0
captain_sprite = spr_captaingoblin
canon_sprite = spr_captaingoblin_canon
canon_index = 0
destroyed = 0
captain_y = obj_screensizer.actual_height
canon_y = obj_screensizer.actual_height
